healthlife_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: healthlifeUserBundle:Default:index }

condition_homepage:
    path:     /show
    defaults: { _controller: healthlifeUserBundle:Default:show }

symptom:
    path:     /symptom
    defaults: { _controller: healthlifeUserBundle:Symptom:index }
    
symptom_new:
    path:     /symptom/new
    defaults: { _controller: healthlifeUserBundle:Symptom:new }

symptom_create:
    path:     /symptom/create
    defaults: { _controller: healthlifeUserBundle:Symptom:create }
    
symptom_show:
    path:     /symptom/show/{id}
    defaults: { _controller: healthlifeUserBundle:Symptom:show }
    
symptom_delete:
    path:     /symptom/delete/{id}
    defaults: { _controller: healthlifeUserBundle:Symptom:delete }
    
symptom_edit:
    path:     /symptom/edit/{id}
    defaults: { _controller: healthlifeUserBundle:Symptom:edit }

symptom_update:
    path:     /symptom/update/{id}
    defaults: { _controller: healthlifeUserBundle:Symptom:update }
    
healthcondition:
    path:     /condition
    defaults: { _controller: healthlifeUserBundle:HealthCondition:index }
    
healthcondition_new:
    path:     /condition/new
    defaults: { _controller: healthlifeUserBundle:HealthCondition:new }

healthcondition_create:
    path:     /condition/create
    defaults: { _controller: healthlifeUserBundle:HealthCondition:create }
    
healthcondition_show:
    path:     /condition/show/{id}
    defaults: { _controller: healthlifeUserBundle:HealthCondition:show }
    
healthcondition_delete:
    path:     /condition/delete/{id}
    defaults: { _controller: healthlifeUserBundle:HealthCondition:delete }
    
healthcondition_edit:
    path:     /condition/edit/{id}
    defaults: { _controller: healthlifeUserBundle:HealthCondition:edit }

healthcondition_update:
    path:     /condition/update/{id}
    defaults: { _controller: healthlifeUserBundle:HealthCondition:update }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_condition_add:
    pattern:  /condition/add/
    defaults: { _controller: healthlifeUserBundle:Default:addcondition }
