parameters:
#    healthlife_user.example.class: healthlife\UserBundle\Example

services:
#    healthlife_user.example:
#        class: %healthlife_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
